version: '3.3'
services:
  web:
   image: nginx:latest
   volumes:
     - ${DOCKER_DEV_PATH}/logs/nginx:/data/logs/nginx
     - ${DOCKER_DEV_PATH}/test_code/php:/code
     - ./site.conf:/etc/nginx/conf.d/default.conf
   depends_on:
     - php
   networks:
     - traefik_proxy
   deploy:
     mode: replicated
     replicas: 2
     labels:
        - traefik.backend=nginx
        - traefik.frontend.passHostHeader=true
        - traefik.frontend.rule=Host:domain.cloud-labs.io
        - traefik.docker.network=traefik_proxy
        - traefik.port=80
  php:
   image: php:5.5.38-fpm
   volumes:
    - ./php.ini:/usr/local/etc/php/php.ini
    - ./php-fpm.conf:/usr/local/etc/php-fpm.conf
    - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
    - ${DOCKER_DEV_PATH}/test_code/php:/code
    - ${DOCKER_DEV_PATH}/logs/php:/data/logs/php
   networks:
     - traefik_proxy
   deploy:
     mode: replicated
     replicas: 3
     labels:
        - traefik.enable=false
networks:
  traefik_proxy:
    external: true
